version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.36.1
  - dependency-name: fakerphp/faker
    versions:
    - 1.14.0
